# Generated by Django 4.0.3 on 2022-04-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airplane_name', models.CharField(max_length=200)),
                ('airplane_number', models.IntegerField(max_length=4)),
                ('airplane_date_of_departure', models.DateTimeField(verbose_name='Departure date')),
            ],
        ),
    ]
