# Generated by Django 4.0.4 on 2022-04-27 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_selection', models.CharField(blank=True, max_length=255)),
                ('drink_selection', models.CharField(blank=True, max_length=255)),
                ('movie_selection', models.CharField(blank=True, max_length=255)),
                ('airplane_num', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='airline.airplane')),
                ('user_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
