# Generated by Django 4.0.4 on 2022-04-19 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Singleton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('singleton_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='airline.singleton')),
                ('background_title', models.CharField(choices=[('poop.jpg', 'poop.jpg'), ('fuck.jpg', 'fuck.jpg'), ('bitch.png', 'bitch.png')], max_length=100)),
            ],
            bases=('airline.singleton',),
        ),
    ]
