# Generated by Django 4.0.4 on 2022-04-27 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='airplane_date_of_departure',
            field=models.DateTimeField(null=True, verbose_name='Departure date'),
        ),
    ]
