# Generated by Django 4.0.3 on 2022-04-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0004_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='airplane_number',
            field=models.IntegerField(),
        ),
    ]
