# Generated by Django 4.0.4 on 2022-04-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0004_remove_booking_airplane_num_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuestEmail',
        ),
        migrations.AlterField(
            model_name='booking',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='food_selection',
            field=models.CharField(choices=[('BC', 'Blackened Chicken'), ('NYS', 'New York Strip'), ('ECS', 'Escargot'), ('CAV', 'Caviar'), ('OY', 'Oysters'), ('FG', 'Foie Gras'), ('RMO', 'Rocky Mountain Oysters'), ('CB', 'Creme Brulee'), ('WAG', 'Wagu Beef'), ('BB', 'Baby Back Ribs'), ('CP', 'Chicken Parmesean'), ('NG', 'Nigiri')], default='BR', max_length=22),
        ),
    ]
