# Generated by Django 4.0.4 on 2022-04-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0005_delete_guestemail_alter_booking_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='airplane_destination',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='drink_selection',
            field=models.CharField(blank=True, choices=[('AS', 'Aperol Spritz'), ('JC', 'Jack and Coke'), ('RC', 'Rum and Coke'), ('WW', 'White Wine'), ('RW', 'Red Wine'), ('CH', 'Champage'), ('AS', 'Aperol Spritz'), ('SD', 'Screwdriver'), ('BM', 'Bloody Mary'), ('PIL', 'Pilsner'), ('IPA', 'IPA')], max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='food_selection',
            field=models.CharField(choices=[('BC', 'Blackened Chicken'), ('NYS', 'New York Strip'), ('ECS', 'Escargot'), ('CAV', 'Caviar'), ('OY', 'Oysters'), ('FG', 'Foie Gras'), ('RMO', 'Rocky Mountain Oysters'), ('CB', 'Creme Brulee'), ('WAG', 'Wagu Beef'), ('BB', 'Baby Back Ribs'), ('CP', 'Chicken Parmesean'), ('NG', 'Nigiri')], default='BR', max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='movie_selection',
            field=models.CharField(blank=True, choices=[('BAT', 'Batman'), ('MF', 'Moonfall'), ('IS', 'Interstellar'), ('SP', 'Soul Plane'), ('AP', 'The Adam Project'), ('SM', 'Spiderman'), ('X', 'X'), ('SD', 'Screwdriver'), ('CD', 'Choose or Die'), ('PR', 'Power Rangers'), ('KO', 'Knives Out'), ('PR', 'Power Rangers'), ('WE', 'Suck on That!'), ('MU', 'My Friend Clifford'), ('DW', 'Dick Wildfreds Unlikely Adventure'), ('DS', 'Dwight Schrute')], max_length=255),
        ),
    ]
