# Generated by Django 4.0.3 on 2022-04-21 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0005_alter_airplane_airplane_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
