# Generated by Django 4.0.3 on 2022-04-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0007_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
