# Generated by Django 4.0.3 on 2022-04-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0008_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
